apiVersion: v1
kind: Service
metadata:
  name: vulnerableapp-service
spec:
  type: NodePort
  selector:
    app: vulnerableapp
  ports:
  - protocol: TCP
    nodePort: 32000
    port: 9090
    targetPort: 9090

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnerableapp-deployment
  labels:
    app: vulnerableapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vulnerableapp
  template:
    metadata:
      labels:
        app: vulnerableapp
    spec:
      containers:
      - name: vulnerableapp
        image: georgeder/vulnerableapp:latest
        ports:
        - containerPort: 9090
